language: node_js

sudo: required

node_js:
    - '4'

cache:
    apt: true
    directories:
        - node_modules

install:
    - npm install
    - npm i -g mocha

script:
    - npm test
    - npm run jscs
    - npm run lint

notifications:
  email: false
  slack: test4bmw:e79ZZlomWX5n3kZFe1TikGfS